import { ClerkProvider } from "@clerk/nextjs";
import "../styles/globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "../lib/utils";

export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
};

const fontSans = FontSans({
    subsets: ["latin"],
    variable: "--font-sans",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <ClerkProvider>
            <html lang="en" suppressHydrationWarning>
                <body className={cn("min-h-screen bg-background font-sans antialiased", fontSans.variable)}>
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
